# Analisis exploratorio de datos

In [3]:
import pandas as pd
from pathlib import Path
ruta=Path('../data/ciberseguridad_dataset.csv')
df= pd.read_csv(ruta)

### Muestro los primeros 5 registros:

In [6]:
df.head(5)

,Tipo_Ataque,Tasa_Ocurrencia (%),Vector_Infeccion,Nivel_Impacto (1-10),Tiempo_Recuperacion (horas),Costo_Recuperacion (USD)
0,Phishing,63,Ingeniería social,5,84,8031
1,Phishing,70,Correo electrónico,8,96,612
2,Adware,89,Descarga de archivos,1,4,390
3,Rootkit,16,Vulnerabilidad de red,9,65,37158
4,Phishing,69,Ingeniería social,4,59,2377

### Los últimos 5 registros:

In [5]:
df.tail(5)

,Tipo_Ataque,Tasa_Ocurrencia (%),Vector_Infeccion,Nivel_Impacto (1-10),Tiempo_Recuperacion (horas),Costo_Recuperacion (USD)
9995,Ataque DDoS,26,Vulnerabilidad de red,8,91,34900
9996,Troyano,37,Descarga de archivos,9,41,1039
9997,Troyano,66,Correo electrónico,5,117,14602
9998,Adware,80,Descarga de archivos,2,8,201
9999,Adware,62,Descarga de archivos,3,4,197

### Los tipos de datos y valores nulos:

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tipo_Ataque                  10000 non-null  object
 1   Tasa_Ocurrencia (%)          10000 non-null  int64
 2   Vector_Infeccion             10000 non-null  object
 3   Nivel_Impacto (1-10)         10000 non-null  int64
 4   Tiempo_Recuperacion (horas)  10000 non-null  int64
 5   Costo_Recuperacion (USD)     10000 non-null  int64
dtypes: int64(4), object(2)
memory usage: 468.9+ KB

### La cantidad de filas y columnas del dataset:

In [9]:
filas=df.shape[0]
columnas=df.shape[1]
print(f'El dataset tiene {filas} filas y {columnas} columnas')

El dataset tiene 10000 filas y 6 columnas

### Buscar valores máximos y mínimos:

In [3]:
valor_minimo=df["Costo_Recuperacion (USD)"].min()
valor_maximo=df["Costo_Recuperacion (USD)"].max()
print(f'Valor mínimo: {valor_minimo}')
print(f'Valor máximo: {valor_maximo}')

Valor mínimo: 100
Valor máximo: 49965

### Tipos de ataques:

In [17]:
print(df['Tipo_Ataque'].nunique())

10

### Datos faltantes:

In [ ]:
print(df.isnull())

Tipo_Ataque                    False
Tasa_Ocurrencia (%)            False
Vector_Infeccion               False
Nivel_Impacto (1-10)           False
Tiempo_Recuperacion (horas)    False
Costo_Recuperacion (USD)       False
dtype: bool

### Columnas numericas y categorias:

In [5]:
print(df.dtypes)

Tipo_Ataque                    object
Tasa_Ocurrencia (%)             int64
Vector_Infeccion               object
Nivel_Impacto (1-10)            int64
Tiempo_Recuperacion (horas)     int64
Costo_Recuperacion (USD)        int64
dtype: object

### Tamaño del dataset para extraer conclusiones generales:

In [ ]:
print(df.shape)

(10000, 6)

### Valor con mayor relacion con el costo de recuperacion:

In [ ]:
print(df.corr(numeric_only=True))
# cerca de 1 indica una fuerte correlación positiva, cerca de -1 indica una fuerte correlación negativa, y cerca de 0 indica poca o ninguna correlación.

Costo_Recuperacion (USD)       1.000000
Tiempo_Recuperacion (horas)    0.585714
Nivel_Impacto (1-10)           0.521691
Tasa_Ocurrencia (%)           -0.353968
Name: Costo_Recuperacion (USD), dtype: float64

### Usando describe

In [6]:

print(df.describe())

       Tasa_Ocurrencia (%)  Nivel_Impacto (1-10)  Tiempo_Recuperacion (horas)  \
count         10000.000000           10000.00000                 10000.000000
mean             46.510700               6.28040                    89.694600
std              20.560675               2.24706                    96.115039
min               5.000000               1.00000                     1.000000
25%              31.000000               5.00000                    25.000000
50%              45.000000               7.00000                    60.000000
75%              59.000000               8.00000                   113.000000
max             100.000000              10.00000                   499.000000

       Costo_Recuperacion (USD)
count              10000.000000
mean               11157.293800
std                10965.606444
min                  100.000000
25%                 2715.000000
50%                 7514.000000
75%                15619.000000
max                49965.000000

## Actividad 2

### Impacto promedio

In [25]:
promedio=df.groupby('Tipo_Ataque')["Nivel_Impacto (1-10)"].count()
print(promedio)

Tipo_Ataque
Adware           1185
Ataque DDoS      1006
Botnet            767
Gusano (Worm)     804
Phishing         1519
Ransomware       1216
Rootkit           623
Spyware           896
Troyano           980
Virus            1004
Name: Nivel_Impacto (1-10), dtype: int64